language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

os:
  - linux

env:
  global:
  - CONDA_DEPS_27=""
  - CONDA_DEPS_35=""
  - COVERAGE=true  # Coverage support with codecov
  - FLAKE8=false  # Flake8 style checker


before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install numpy scipy matplotlib pandas  # install dependencies first
  - conda install gdal=2.1.0 libgdal=2.1.0  # Use explicit gdal, libgdal
  - if [[ "$COVERAGE" == "true" ]]; then  
      conda install pytest-cov codecov  # Test coverage stats
    else
      conda install pytest
    fi
  - python setup.py install

script:
  - if [[ "$COVERAGE" == "true" ]]; then  
      py.test --cov=./  # cov flag will output coverage
    else
      py.test
    fi

after_success:
  # attempts to upload to codecov, but does not fail build if codecov fails
  if [[ "$COVERAGE" == "true" ]]; then
    codecov || echo "codecov upload failed"  
  fi