language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda2/bin:$PATH
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION anaconda numpy scipy gdal matplotlib pandas
  - source activate test-env
  - python setup.py install
script:
  - py.test