language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.6

env:
  global:
  - COVERAGE=true  # Coverage support with codecov
  - FLAKE8=false  # Flake8 style checker


before_install:
  - ./travis/before_install.sh

install:
  # Activate conda environment tes-env created in before_install.sh
  - export PATH=$HOME/miniconda/bin:$PATH
  - source activate test-env
  # Install from file
  - conda install --yes --file requirements_conda.txt
  - conda list
  # Install craterpy
  - python setup.py install

script:
  # Run tests with the --cov flag to check coverage
  - if  [[ "$COVERAGE" == "true" ]]; then
    conda install --yes pytest-cov codecov;
    py.test --cov=./;
    fi

after_success:
  # Tries to upload coverage to codecov, but does not fail build if upload fails
  - if [[ "$COVERAGE" == "true" ]]; then
    codecov || echo "codecov upload failed";
    fi
  - echo "Build success"
