language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

os:
  - linux

env:
  global:
  - CONDA_DEPS_27="anaconda flake8 sphinx pytest numpy scipy matplotlib pandas gdal=1.11.2"
  - CONDA_DEPS_35="anaconda flake8 sphinx pytest numpy scipy matplotlib pandas gdal libgdal=2.0.0"


before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - conda install pytest numpy scipy matplotlib pandas 
  - conda install gdal=2.1.0 libgdal=2.1.0
  - python setup.py install

script:
  - py.test
