language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.4


env:
  global:
  - CONDA_DEPS_27=false
  - CONDA_DEPS_35=false
  - COVERAGE=true  # Coverage support with codecov
  - FLAKE8=false  # Flake8 style checker


before_install:
  - ./travis/before_install.sh

install:
  # Create and activate conda environment
  - export PATH=$HOME/miniconda/bin:$PATH
  - source activate test-env
  # Install non gdal dependencies
  - conda install pytest pytest-cov numpy scipy matplotlib pandas
  # Install gdal, libgdal and explicitly state versions to avoid mismatch bug
  - conda install gdal=2.1.0 libgdal=2.1.0
  # Upload test coverage stats with codecov
  - pip install codecov
  - python setup.py install

script:
  # Use the --cov flag to pytest-cov to run coverage stats
  - py.test --cov=./
    
after_success:
  # Tries to upload coverage to codecov, but does not fail build if upload fails
  - if [[ "$COVERAGE" == "true" ]]; then
    codecov || echo "codecov upload failed";
    fi
  - echo "Build success"
