os:
  - linux

language: python

env:
  global:
    - CONDA_DEPS="anaconda flake8 pytest numpy scipy matplotlib pandas gdal"

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set anaconda_upload no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
  - source activate test-env
  - python setup.py install

script:
  - py.test
  - flake8