[tool.poetry]
name = "craterpy"
version = "0.3.1"
description = "A package for impact crater data science."
authors = ["Christian J. Tai Udovicic <cj.taiudovicic@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.7"
numpy = "^1.20.2"
matplotlib = "^3.4.2"
pandas = "^1.2.4"
rasterio = "^1.2.3"


[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
